name: wechat_camera_picker_demo
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 3.0.0+4

environment:
  sdk: '>=2.14.0 <3.0.0'
  flutter: '>=2.5.0'

dependencies:
  flutter:
    sdk: flutter

  wechat_camera_picker:
    path: ../
  wechat_assets_picker: 7.0.0-dev.4
  native_device_orientation: ^1.0.0
  image: ^3.1.3

flutter:
  uses-material-design: true
